---
- name: Setup Instance
  hosts: 
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: activate venv
      shell: "source ~/venv/openstack/bin/activate"
      args:
        executable: /bin/bash

    - name: activate remote as admin
      shell: "source yuga-admin.sh"
      args:
        executable: /bin/bash 
    
    - name: create intance master
      shell: "openstack server create kyuga-master --image ubuntu-focal-amd64 --flavor m1.large --security-group allow-any --key-name region3-key --network cluster-yuga --host region3-key --os-compute-api-version 2.74"
      args:
        executable: /bin/bash 
        
    - name: create intance worker-1
      shell: "openstack server create kyuga-worker-1 --image ubuntu-focal-amd64 --flavor m1.large --security-group allow-any --key-name region3-key --network cluster-yuga --host region3-key --os-compute-api-version 2.74"
      args:
        executable: /bin/bash 
        
    
    - name: create intance worker-2
      shell: "openstack server create kyuga-worker-2 --image ubuntu-focal-amd64 --flavor m1.large --security-group allow-any --key-name region3-key --network cluster-yuga --host region3-key --os-compute-api-version 2.74"
      args:
        executable: /bin/bash 
